#ifndef SHADERS_SMAA_SMAA_GLSL
#define SHADERS_SMAA_SMAA_GLSL

#define SMAA_GLSL4 1
#define SMAA_RT_METRICS vec4(1.0 / TARGET_WIDTH, 1.0 / TARGET_HEIGHT, TARGET_WIDTH, TARGET_HEIGHT)
#define SMAA_PRESET_LOW
//SMAA_PRESET_MEDIUM
//SMAA_PRESET_HIGH
//SMAA_PRESET_ULTRA

#if defined(VERTEX_SHADER)
#define SMAA_INCLUDE_VS
#elif defined(FRAGMENT_SHADER)
#define SMAA_INCLUDE_PS
#endif

#include "SMAA.hlsl"

#endif // SHADERS_SMAA_SMAA_GLSL
